In [1]:
import numpy as np

In [2]:
A = np.matrix([[1, 0.3], [0.45, 1.2]])
U, s, V = np.linalg.svd(A)

In [22]:
A

matrix([[1.  , 0.3 ],
        [0.45, 1.2 ]])

In [23]:
U

matrix([[-0.58189652, -0.81326284],
        [-0.81326284,  0.58189652]])

In [24]:
s

array([1.49065822, 0.71444949])

In [25]:
np.diag(s)

array([[1.49065822, 0.        ],
       [0.        , 0.71444949]])

In [26]:
V

matrix([[-0.63586997, -0.77179621],
        [-0.77179621,  0.63586997]])

In [27]:
# Verify calculation of A=USV
np.allclose(A, U * np.diag(s) * V)

True

In [6]:
# Verify orthonormal properties of U and V. (Peformed on U but the same applies for V).
# Dot product between columns = 0 (行內積會等於 0)
np.round([np.dot(U[:, i-1].A1,  U[:, i].A1) for i in range(1, len(U))])

array([-0., -0.])

In [31]:
U[:, 1-1].A1

array([-0.58189652, -0.81326284])

In [32]:
U[:, 1].A1

array([-0.81326284,  0.58189652])

In [29]:
# Multiplying by its transpose = identity matrix
np.allclose(U.T * U, np.identity(len(U)))

True

In [30]:
# U.T * U = U*U.T
np.allclose(U * U.T, U.T * U)

True

In [2]:
# Try it
B = np.matrix([[5, 0.3, 1], [0.45, 1.2, 3], [0.45, 1.2, 3]])
C = np.matrix([[2, 0.3, 1, 7], [5, 6, 3, 7], [1, 2, 3, 7],[1, 5, 7, 9]])