In [2]:
import numpy as np

In [3]:
A = np.matrix([[1, 0.3], [0.45, 1.2]])
U, s, V = np.linalg.svd(A)

In [4]:
U

matrix([[-0.58189652, -0.81326284],
        [-0.81326284,  0.58189652]])

In [5]:
s

array([1.49065822, 0.71444949])

In [7]:
V

matrix([[-0.63586997, -0.77179621],
        [-0.77179621,  0.63586997]])

In [8]:
# Verify calculation of A=USV
np.allclose(A, U * np.diag(s) * V)

True

In [10]:
# Verify orthonormal properties of U and V. (Peformed on U but the same applies for V).
#  1) Dot product between columns = 0
np.round([np.dot(U[:, i-1].A1,  U[:, i].A1) for i in range(1, len(U))])

array([-0.])

In [11]:
#  2) Columns are unit vectors 單位向量 (length = 1) 
np.round(np.sum((U*U), 0))

matrix([[1., 1.]])

In [12]:
#  3) Multiplying by its transpose = identity matrix
np.allclose(U.T * U, np.identity(len(U)))

True